### ISSUE TITLE
How to build mappability file

### ISSUE THREAD

**Issue by rachelzhu123** [yycunc/FIREcaller#1]
Dear Yun Li,
I am interested in using FIREcaller on my Hic data which have been processed using Juicer and pairtools.  To use FIREcaller, I need to prepare two input file, .hic and mappability file. The reference genome I use is pig, and the resolution of the matrix is 5KB. So I have to build mappability file.  But after reading README.md and tutorial (https://yunliweb.its.unc.edu/FIREcaller/software/FIRECaller_RMD.html), I still don't quite understand the contents of the third column to the seventh column in the mappability file. How should I build mappability file?  Hope to get your answer.
## 6 chr1 200000 240000   0 0.0000 0.0000   0

**Comment by yycunc** [comment]
Hi,

Here is a link for the script for calculating local genomic features:

http://www.people.fas.harvard.edu/~junliu/HiCNorm/

Please let me know if you still have any problem.

**Comment by rarara2333** [comment]
> Hi,
> 
> Here is a link for the script for calculating local genomic features:
> 
> http://www.people.fas.harvard.edu/~junliu/HiCNorm/
> 
> Please let me know if you still have any problem.

Hi,

The script is only worked for 6-base cutter (such as Hind3), but if we want to do it for a 4-base cutter (such as Mbol), is there any solution?

Would be appreciated for your reply.

**Comment by yycunc** [comment]
Hi，

Sorry for my late response. My collaborator slightly modified the script for genomic features calculation to allow for other restriction enzymes. The script is here: https://github.com/HuMingLab/MAPS/tree/master/bin/utils/genomic_features_generator.

It includes a readme file that has some details on how to run and gives an example for generating features from HhaI res. enzyme

Does it solve your problem?

Bests,

Yuchen

--
Yuchen Yang, Ph.D.
Research Assistant Professor
Department of Pathology and Laboratory Medicine
McAllister Heart Institute
Medical Biomolecular Research Bldg.
University of North Carolina at Chapel Hill
111 Mason Farm Road
Chapel Hill, NC, 27599
He / him / his


From: rarara2333 ***@***.***>
Reply-To: yycunc/FIREcaller ***@***.***>
Date: Monday, July 26, 2021 at 2:36 AM
To: yycunc/FIREcaller ***@***.***>
Cc: yyuchen ***@***.***>, Comment ***@***.***>
Subject: Re: [yycunc/FIREcaller] How to build mappability file (#1)


Hi,

Here is a link for the script for calculating local genomic features:

http://www.people.fas.harvard.edu/~junliu/HiCNorm/

Please let me know if you still have any problem.

Hi,

The script is only worked for 6-base cutter (such as Hind3), but if we want to do it for a 4-base cutter (such as Mbol), is there any solution?

Would be appreciated for your reply.

**Comment by canfeng-HUA** [comment]
Thanks a lot for your comments. I used genomic_features_generator to generate genomic_features. But, the result had a little different from the sample you provided. I only got 6 columns, not 7. Besides, there is no header in my results. 
![image](https://user-images.githubusercontent.com/71436402/141106717-1b4eec35-4f51-461c-a998-a186a53af423.png)

**Comment by weifangliu** [comment]
The columns should be in this order: chr start end F GC M. The 7th column should be EBL, which is a binary variable that takes 0 or 1 which tells if this bin is in ENCODE blacklisted genomic regions. I am not aware of any ENCODE blacklisted genomic regions for the pig genome, but if you have blacklist region data, you can merge that with your current mappability file using the R script `mappability.R` that we recently added to the repository. If there is no available blacklist region data, probably the easiest thing you can do for now is to manually add an 7th column with all zeros in your current mappability data. We have also updated the readme accordingly which you can refer to.

**Comment by yunliUNC** [comment]
Thanks, Weifang!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
