### ISSUE TITLE
Compatible with enrichment based capturing methods

### ISSUE THREAD

**Issue by SplitInf** [yycunc/FIREcaller#6]
Hi, I'm wondering if FIREcaller is compatible with enrichment based capturing methods like CHIA-PET / HiChIP? It seems that  the algorithm is based on Z score of interactions so not sure if enrichment will break the assumptions. Perhaps this be remedied by intersecting with corresponding ChIPSeq peaks.

**Comment by yunliUNC** [comment]
Thanks for the email. Unfortunately, FIRE-caller is designed for Hi-C data and do not work with enrichment based method. We hope to extend the method to handle such data. Yun
________________________________
From: SplitInf ***@***.***>
Sent: Saturday, April 23, 2022 12:07 AM
To: yycunc/FIREcaller ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yycunc/FIREcaller] Compatible with enrichment based capturing methods (Issue #6)


Hi, I'm wondering if FIREcaller is compatible with enrichment based capturing methods like CHIA-PET / HiChIP?
